---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  product_name: chef
  product_version: 12.21.26

verifier:
  name: inspec

platforms:
  - name: centos-7.2
  - name: ubuntu-14.04
    run_list:
      - recipe[apt::default]
  - name: ubuntu-16.04
    run_list:
      - recipe[apt::default]

suites:
  - name: default
    run_list:
      - recipe[elastic_repo::default]
    attributes:
